project_id = "xqnqssvypvwnedpaylwz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://xqnqssvypvwnedpaylwz.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.assistant-chat]
verify_jwt = true

[functions.calendar-integration]
verify_jwt = true

[functions.email-integration]
verify_jwt = true

[functions.oauth-callback]
verify_jwt = false