// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqnqssvypvwnedpaylwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxbnFzc3Z5cHZ3bmVkcGF5bHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTY1MjgsImV4cCI6MjA2OTA5MjUyOH0.zEo80CWmBR38anzKkcvZmXui7uvEQVhO9g_B7Q7WOmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});